services:
  libreads:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreads-dev
    user: 1000:1000
    environment:
      - LIBREADS_BASE_URL=https://libreads.local
      - LIBREADS_AUTH_SECRET=supersecretkeythatshouldbereplacedinproduction
    volumes:
      - ./.libreads/docker:/data
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: libreads-dev-proxy
    depends_on:
      - libreads
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.libreads/caddy/data:/data
      - ./.libreads/caddy/config:/config
    restart: unless-stopped
